name: Merge Master Back To Develop
on:
    workflow_dispatch:
    push:
        branches:
            - master

    merge-back:
      runs-on: ubuntu-latest
      - name: Checkout
        uses: actions/checkout@v2
        with:
            ref: develop

      - name: merge
        run: |
            git fetch
            git merge master
            git push

