name: Create Github Release
on:
  pull_request:
      #types: [closed]
    branches:
        - master

jobs:
  create-release:
      #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Tag From Branch
        id: extract_tag
        shell: bash
        run: | 
            echo "##[set-output name=release;]$(echo ${GITHUB_REF#refs/heads/} | cut -f1 -d'/')"
            echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/heads/} | cut -f2 -d'/')"

      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
        version: ${{ steps.extract_tag.outputs.tag }}

      - name: Create release
        if: ${{ steps.extract_tag.outputs.release }} == 'release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag }}
          release_name: ${{ steps.extract_tag.outputs.tag }}
          draft: false
          prerelease: false
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
